# Lab 14 Neural Network

In [36]:
#Imports
import numpy as np 

###  Task :: Make a Neural Network from scratch. It will be a two layer Neural network. You have to perform feedforward to calcluate the output. Along with this we will have to perform backpropagation to update the wights according to the loss.The following steps will be guidelines that will help you along the way. 
 


In [37]:
# Step 1 : Make a neural network class that has attributes : input , weightsFirstLayer , weightsSecondLayer , provided output ,
#         and calculated output(should be similar shape as provided output). The weights should be initialized at random.

# --Help for Step 1--
# Size of weights for first layer: As your input has an array of 3 features(cols) and their respective 4 rows.
# Size of weights for second layer: As now your iput  is the result of first layer(four values) mutiplied with weights.

# Step 2: Follow the algo written in feed forward

# Step 3: Follow algo of bakpropogate (Here the lecture comes in handy)

# Step 4: Run fun as is

# Step 5: Ask me for runner code

class NeuralNetwork():
    def __init__(self, x, y):
        self.w1 = np.random.rand(3, 4)
        self.w2 = np.random.rand(4, 1)
        self.x = x
        self.y = y

    def sigmoid(self, t):
        return 1 / (1 + np.exp(-t))

    def sigmoid_derivative(self, p):
        return p * (1 - p)

    def feedforward(self):
        FirstLayer = self.sigmoid(np.dot(self.x, self.w1))
        SecLayer = self.sigmoid(np.dot(FirstLayer, self.w2))
        return FirstLayer, SecLayer

    def backpropogate(self, first, second):
        # For last layer weights
        # d1_w = a^(l-1)*Sig(a^(l))*2(out-a^(l))
        d1_w = np.dot(np.transpose(np.squeeze(np.asarray(first))), np.dot(
            self.sigmoid_derivative(np.squeeze( np.asarray(second))), 2 * (self.y - np.squeeze(np.asarray(second)))))
        # For Sec last layer weights
        # d2_w = a^(l-2)*Sig(a^(l))*2(out-a^(l))*W2*Sig(a^(l-1))
        # d2_w = np.dot(
        d2_w =  np.dot(np.transpose(self.x), 
        np.dot(self.sigmoid_derivative( 
            np.squeeze( np.asarray(second))),  
        2 * (self.y - np.squeeze( np.asarray(second)))))
        # np.dot(self.w1,  self.sigmoid_derivative(np.squeeze(np.asarray(first)))))
        self.w2 = np.add(self.w2, d1_w)
        temp = np.zeros(np.shape(self.w1))
        #print(np.matrix(d2_w))
        # self.w1 = np.add(self.w1, n)
        # print(np.matrix(self.w1))
        # print(np.matrix(d1_w))
        # np.add(self.w2, d2_w)
        # Add them to exisiting weights

    def Train(self):
        First, Second = self.feedforward()
        self.backpropogate(First, Second)


if __name__ == '__main__':
    # input = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=float)
    # output = np.array([[0], [1], [1], [0]], dtype=float)
    X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=float)
    y = np.array([[0], [1], [1], [0]], dtype=float)
    NN = NeuralNetwork(X, y)
    for i in range(1500):
        if i % 100 == 0:
            print("for iteration # " + str(i) + "\n")
            print("Input : \n" + str(X))
            print("Actual Output:  \n" + str(y))
            First, Second = NN.feedforward()
            print("Predicted Output : \n", np.matrix(Second))
            print("Loss:  \n" + str(np.mean(np.square(y - Second))))
            print("\n")
        NN.Train()


for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output:  
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output : 
 [[0.86471804]
 [0.90085259]
 [0.90337686]
 [0.9228109 ]]
Loss:  
0.4046208733449593


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output:  
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output : 
 [[0.80930545 0.80966506 0.80970319 0.80967539]
 [0.84773186 0.84752616 0.84765755 0.84754085]
 [0.85282294 0.85287157 0.85271223 0.85285089]
 [0.87452418 0.87421991 0.87420529 0.87421346]]
Loss:  
0.36617522811652486


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output:  
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output : 
 [[0.71333186 0.72619776 0.72755136 0.72656201]
 [0.74773315 0.7608527  0.76244233 0.76125156]
 [0.75434094 0.76771883 0.76888566 0.76806419]
 [0.77513723 0.78847035 0.78988802 0.78884817]]
Loss:  
0.3136207517650549


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]